server:
  port: 1010
  servlet:
    context-path: /api
spring:
  application:
    name: el-aparato
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:elaparato
    username: root
  h2:
    console:
      enabled: true
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  sql:
    init:
      data-locations: classpath:/sql_base_elaparato.sql
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/el-aparato-pablocamejo
        registration:
          keycloak:
            client-id: ${client-id}
            client-secret: ${client-secret}
            redirect-uri: http://localhost:8081/login/oauth2/code/keycloak
jwt:
  auth:
    converter:
      resource-id: backend-el-aparato
      principal-attribute: preferred_username
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
      springframework:
        security: DEBUG
