server:
  port: 9090
spring:
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: el-aparato
          predicates:
            - Path=/api/**
          uri: http://localhost:8081
  security:
    oauth2:
      client:
        provider:
          keycloak-test:
            issuer-uri: http://localhost:8080/realms/el-aparato-pablocamejo
        registration:
          keycloak-test:
            authorization-grant-type: authorization_code
            client-id: ${client-id}
            client-secret: ${client-secret}
            redirect-uri: http://localhost:9090/login/oauth2/code/keycloak
            scope:
              - openid
